@OrderService_HostAddress = https://localhost:7117
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImp0aSI6IjQ3MzYzOGQ4LTk4NWEtNGMyZi1hOTQwLWM4YjRmM2VhNGM3OCIsImlhdCI6MTc4MjE5MjM2OCwiZXhwIjoxNzgyMTk1OTY4LCJpc3MiOiJvcmRlcnNlcnZpY2UtYXBpIiwiYXVkIjoib3JkZXJzZXJ2aWNlLWNsaWVudHMifQ.refK3ipwIgveWrC1klHD02_tYCXmoWoLwod4Xb41Jlg

### Auth — Register
POST {{OrderService_HostAddress}}/auth/register
Content-Type: application/json
{
  "username": "admin",
  "password": "admin"
}

### Auth — Login
POST {{OrderService_HostAddress}}/auth/token
Content-Type: application/json
{
  "username": "admin",
  "password": "admin"
}

### Orders — Create Order
POST {{OrderService_HostAddress}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "customerId": 1,
  "currency": "BRL",
  "items": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 4,
      "quantity": 4
    }
  ]
}

### Orders — Confirm Order
POST {{OrderService_HostAddress}}/orders/99d1108d-48eb-4586-9ef4-0949bce8d981/confirm
Content-Type: application/json
Authorization: Bearer {{token}}
